// 'use client'
import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import '@/public/css/all.min.css';
import '@/public/css/bootstrap.min.css';
import '@/public/css/main.css';
import Header from './components/header';
import Footer from './components/footer';



const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});
const lang = {
  lang: "English",
  setLang: (newName: string) => lang.lang = newName,
}
export const metadata: Metadata = {
  title: "ShopGrids",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
          <Header />
          {children}
          <Footer />
      </body>
    </html>
  );
}
